name: Test

on:
  workflow_call:

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.3'
          elixir-version: '1.18.4'

      - uses: ./.github/actions/setup-elixir

      - name: Wait for Postgres
        run: |
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 && break
            sleep 1
          done

      - name: Run tests
        run: mix test
